const has=(t,w)=>w.some(x=>t.includes(x));
const localized={
hi:{loan:['उधारकर्ता','ऋणदाता','सहमति के अनुसार मूलधन, ब्याज और वैध शुल्क समय पर चुकाएँ।','सहमत राशि दें और दरें, शुल्क तथा चूक के परिणाम स्पष्ट बताएँ।'],rental:['किरायेदार','मकान मालिक','सहमत किराया और शुल्क समय पर दें तथा परिसर का उचित उपयोग करें।','परिसर उपलब्ध कराएँ और अपनी जिम्मेदारियाँ पूरी करें।'],employment:['कर्मचारी','नियोक्ता','निर्धारित भूमिका निभाएँ और वैध कार्यस्थल नियमों का पालन करें।','सहमत वेतन दें और वादा की गई कार्य शर्तें प्रदान करें।'],service:['ग्राहक','सेवा प्रदाता','वैध शुल्क समय पर दें और आवश्यक जानकारी प्रदान करें।','सहमत सेवाएँ दें और सही बिल जारी करें।']},
kn:{loan:['ಸಾಲಗಾರ','ಸಾಲದಾತ','ಒಪ್ಪಂದದಂತೆ ಮೂಲಧನ, ಬಡ್ಡಿ ಮತ್ತು ಮಾನ್ಯ ಶುಲ್ಕಗಳನ್ನು ಸಮಯಕ್ಕೆ ಪಾವತಿಸಿ.','ಒಪ್ಪಿದ ಮೊತ್ತವನ್ನು ನೀಡಿ ಮತ್ತು ದರ, ಶುಲ್ಕ ಹಾಗೂ ಡೀಫಾಲ್ಟ್ ಪರಿಣಾಮಗಳನ್ನು ಸ್ಪಷ್ಟಪಡಿಸಿ.'],rental:['ಬಾಡಿಗೆದಾರ','ಮನೆಮಾಲೀಕ','ಒಪ್ಪಿದ ಬಾಡಿಗೆ ಮತ್ತು ಶುಲ್ಕಗಳನ್ನು ಸಮಯಕ್ಕೆ ಪಾವತಿಸಿ ಹಾಗೂ ಆವರಣವನ್ನು ಸರಿಯಾಗಿ ಬಳಸಿ.','ಆವರಣ ನೀಡಿ ಮತ್ತು ಮನೆಮಾಲೀಕರ ಜವಾಬ್ದಾರಿಗಳನ್ನು ಪೂರೈಸಿ.'],employment:['ಉದ್ಯೋಗಿ','ಉದ್ಯೋಗದಾತ','ನಿಗದಿತ ಕೆಲಸ ಮಾಡಿ ಮತ್ತು ಕಾನೂನುಬದ್ಧ ನಿಯಮಗಳನ್ನು ಪಾಲಿಸಿ.','ಒಪ್ಪಿದ ವೇತನ ನೀಡಿ ಮತ್ತು ಭರವಸೆ ನೀಡಿದ ಕೆಲಸದ ಷರತ್ತುಗಳನ್ನು ಒದಗಿಸಿ.'],service:['ಗ್ರಾಹಕ','ಸೇವಾ ಪೂರೈಕೆದಾರ','ಮಾನ್ಯ ಶುಲ್ಕಗಳನ್ನು ಸಮಯಕ್ಕೆ ಪಾವತಿಸಿ ಮತ್ತು ಅಗತ್ಯ ಮಾಹಿತಿ ನೀಡಿ.','ಒಪ್ಪಿದ ಸೇವೆಗಳನ್ನು ನೀಡಿ ಮತ್ತು ಸರಿಯಾದ ಬಿಲ್ ನೀಡಿ.']},
ta:{loan:['கடனாளர்','கடன் வழங்குநர்','ஒப்பந்தப்படி அசல், வட்டி மற்றும் செல்லுபடியான கட்டணங்களைச் செலுத்தவும்.','ஒப்பந்தத் தொகையை வழங்கி விகிதங்கள், கட்டணங்கள் மற்றும் தவறின் விளைவுகளைத் தெளிவுபடுத்தவும்.'],rental:['வாடகையாளர்','வீட்டு உரிமையாளர்','ஒப்பந்த வாடகை மற்றும் கட்டணங்களை நேரத்தில் செலுத்தவும்.','வீட்டை ஒப்படைத்து உரிமையாளர் கடமைகளை நிறைவேற்றவும்.']},
te:{loan:['రుణగ్రహీత','రుణదాత','ఒప్పందం ప్రకారం అసలు, వడ్డీ మరియు చెల్లుబాటు అయ్యే రుసుములను చెల్లించండి.','ఒప్పుకున్న మొత్తాన్ని ఇచ్చి రేట్లు, రుసుములు మరియు డిఫాల్ట్ పరిణామాలను స్పష్టంగా చెప్పండి.'],rental:['అద్దెదారు','ఇంటి యజమాని','ఒప్పుకున్న అద్దె మరియు రుసుములను సమయానికి చెల్లించండి.','ప్రాంగణాన్ని అందించి యజమాని బాధ్యతలను నెరవేర్చండి.']},
bn:{loan:['ঋণগ্রহীতা','ঋণদাতা','সম্মতি অনুযায়ী মূলধন, সুদ ও বৈধ ফি সময়মতো পরিশোধ করুন।','সম্মত অর্থ দিন এবং হার, ফি ও খেলাপির ফল স্পষ্ট করুন।'],rental:['ভাড়াটিয়া','বাড়িওয়ালা','সম্মত ভাড়া ও ফি সময়মতো দিন এবং প্রাঙ্গণ চুক্তি অনুযায়ী ব্যবহার করুন।','প্রাঙ্গণের দখল দিন এবং বাড়িওয়ালার দায়িত্ব পালন করুন।'],employment:['কর্মচারী','নিয়োগকর্তা','নির্ধারিত কাজ করুন এবং বৈধ কর্মক্ষেত্রের নিয়ম মানুন।','সম্মত বেতন দিন এবং প্রতিশ্রুত কাজের শর্ত প্রদান করুন।'],service:['গ্রাহক','পরিষেবা প্রদানকারী','বৈধ ফি সময়মতো দিন এবং প্রয়োজনীয় তথ্য দিন।','সম্মত পরিষেবা দিন এবং সঠিক বিল প্রদান করুন।']}
};
export function deriveObligations(clause,lang='en'){const t=(clause.original_text||'').toLowerCase();let type=has(t,['loan','borrower','lender','principal','interest'])?'loan':has(t,['employee','employer','salary','employment'])?'employment':has(t,['service provider','customer','client','services'])?'service':has(t,['rent','tenant','landlord','lease'])?'rental':'general';const base={loan:['Borrower','Lender','Repay agreed principal, interest, and valid charges on schedule.','Disburse the agreed amount and clearly disclose rates, fees, and default consequences.'],employment:['Employee','Employer','Perform the stated role and follow lawful workplace requirements.','Pay agreed compensation and provide promised employment conditions.'],service:['Customer','Service Provider','Pay valid fees and provide required inputs on time.','Deliver the stated services and issue accurate invoices.'],rental:['Tenant','Landlord','Pay agreed rent and charges on time and use the premises as agreed.','Provide possession and perform landlord responsibilities.'],general:['Party A','Party B','Perform the obligations assigned to Party A.','Perform the obligations assigned to Party B.']}[type];const v=localized[lang]?.[type]||base;return{applicant_label:v[0],recipient_label:v[1],applicant_obligations:[v[2]],recipient_obligations:[v[3]]}}
