const en = {
  section: 'Section', timeline: 'Timeline & Notice Period Visualizer', jurisdictionAwareness: 'Jurisdiction Awareness', emergency: 'Emergency Red Flag Alerts', rights: 'Rights Violation Heat Index', noEmergency: 'No emergency red-flag pattern was detected.',
  jurisdiction: 'Jurisdiction', notSpecified: 'Not specified', jurisdictionMissing: 'Jurisdiction is not specified, so enforceability and applicable law cannot be assessed reliably.',
  timelinePeriods: 'Timeline & notice periods', noTimeline: 'No clear timeline is specified. This may be legally risky.',
  emergencyHeading: 'Emergency red flags', emergencyIntro: 'These clauses may remove important legal protections. Seek qualified legal advice before signing.', violatedRights: 'Rights potentially violated', legalEffect: 'The exact legal effect depends on the document, facts, and applicable law.',
  rightsIndex: 'Rights Violation Heat Index', rightsConcern: 'Potential rights concerns were detected and categorized below.', noRightsConcern: 'No indexed rights compromise was detected.', low: 'Low', medium: 'Medium', high: 'High',
  accessJustice: 'Access to justice', fairTerms: 'Fair contract terms', privacy: 'Privacy', consumerRights: 'Consumer rights', employmentRights: 'Employment rights', housingRights: 'Housing rights', financialRights: 'Financial rights',
  reportSections: 'Report sections', selectSection: 'Select any section to open it', navSummary: 'Agreement summary', navTimeline: 'Timeline & notice periods', navJurisdiction: 'Jurisdiction awareness', navEmergency: 'Emergency red flags', navRights: 'Rights heat index', navLaws: 'Applicable laws', navClauseSummary: 'Clause summary', navSearch: 'Search document', navReview: 'Color-coded review', navPenalties: 'Penalties & compensation', navHidden: 'Hidden costs', navLetter: 'Negotiation letter', navHelp: 'Legal help',
  laws: 'Applicable laws and rules', lawsCaption: "References activated by this document's matched rules. Applicability still depends on the jurisdiction and facts.", noLaws: 'No legal reference was activated by the matched rules. This does not mean no law applies.', verification: 'Verification needed', applicable: 'Applicable reference',
  search: 'Search this document', searchCaption: 'Search by section, wording, obligation, payment, notice period, rule, or topic.', searchPlaceholder: 'Search document sections, for example: deposit, renewal, notice…', clear: 'Clear', matches: 'matching sections found', oneMatch: 'matching section found', needsReview: 'Needs review', acceptable: 'Appears acceptable', viewReview: 'View in clause review', noMatch: 'No matching section was found. Try a shorter term or wording from the agreement.',
  reviewReason: 'Review reason', automatedReview: 'Automated document review', reviewExplanation: 'This clause contains terms that may need clarification or negotiation.', needsAttention: 'Needs attention',
  power: 'Negotiation power estimate', powerNote: 'An estimate based on flagged clauses, not a certified legal score.',
  tracker: 'Penalty & Compensation Tracker', applicantPenalties: 'Applicant penalties', trigger: 'Trigger', consequence: 'Consequence', fairness: 'Fairness check', fairnessNote: 'Check whether this consequence is clear, mutual, capped, and proportionate.', agreementTerm: 'Agreement term', noAmount: 'No amount is expressly stated',
  letter: 'Negotiation letter', copy: 'Copy letter', copied: 'Copied', letterCaption: 'A clause-specific draft ready to personalize and send. Confirm every detail and legal reference independently.', legalHelp: 'Get human legal help', legalHelpIntro: 'If this feels serious, these organizations can help for free or low cost.',
  disclaimerTitle: 'Understand your options—not a legal opinion', disclaimerFallback: 'This is not legal advice. Consult a licensed professional for decisions specific to your situation.', download: 'Download complete PDF report',
};

const hi = {
  section:'अनुभाग',timeline:'समयरेखा और नोटिस अवधि',jurisdictionAwareness:'क्षेत्राधिकार जानकारी',emergency:'आपातकालीन चेतावनियाँ',rights:'अधिकार उल्लंघन सूचकांक',noEmergency:'कोई आपातकालीन चेतावनी नहीं मिली।',jurisdiction:'क्षेत्राधिकार',notSpecified:'निर्दिष्ट नहीं',jurisdictionMissing:'क्षेत्राधिकार निर्दिष्ट नहीं है, इसलिए लागू कानून का विश्वसनीय आकलन नहीं हो सकता।',timelinePeriods:'समयरेखा और नोटिस अवधि',noTimeline:'कोई स्पष्ट समयरेखा नहीं दी गई है। यह कानूनी जोखिम हो सकता है।',emergencyHeading:'आपातकालीन चेतावनियाँ',emergencyIntro:'ये धाराएँ महत्वपूर्ण कानूनी सुरक्षा हटा सकती हैं। हस्ताक्षर से पहले योग्य कानूनी सलाह लें।',violatedRights:'संभावित रूप से उल्लंघित अधिकार',legalEffect:'सटीक कानूनी प्रभाव दस्तावेज़, तथ्यों और लागू कानून पर निर्भर करता है।',rightsIndex:'अधिकार उल्लंघन सूचकांक',rightsConcern:'संभावित अधिकार संबंधी चिंताएँ मिली हैं।',noRightsConcern:'कोई सूचीबद्ध अधिकार उल्लंघन नहीं मिला।',low:'कम',medium:'मध्यम',high:'उच्च',accessJustice:'न्याय तक पहुँच',fairTerms:'निष्पक्ष अनुबंध शर्तें',privacy:'गोपनीयता',consumerRights:'उपभोक्ता अधिकार',employmentRights:'रोज़गार अधिकार',housingRights:'आवास अधिकार',financialRights:'वित्तीय अधिकार',
  reportSections:'रिपोर्ट अनुभाग',selectSection:'खोलने के लिए कोई अनुभाग चुनें',navSummary:'समझौते का सार',navTimeline:'समयरेखा और नोटिस',navJurisdiction:'क्षेत्राधिकार',navEmergency:'आपात चेतावनियाँ',navRights:'अधिकार सूचकांक',navLaws:'लागू कानून',navClauseSummary:'धारा सारांश',navSearch:'दस्तावेज़ खोजें',navReview:'रंग-कोडित समीक्षा',navPenalties:'जुर्माना और मुआवज़ा',navHidden:'छिपी लागत',navLetter:'बातचीत पत्र',navHelp:'कानूनी सहायता',
  laws:'लागू कानून और नियम',lawsCaption:'दस्तावेज़ में मिले नियमों से सक्रिय संदर्भ। लागू होना क्षेत्राधिकार और तथ्यों पर निर्भर है।',noLaws:'कोई कानूनी संदर्भ सक्रिय नहीं हुआ। इसका अर्थ यह नहीं कि कोई कानून लागू नहीं होता।',verification:'सत्यापन आवश्यक',applicable:'लागू संदर्भ',
  search:'इस दस्तावेज़ में खोजें',searchCaption:'अनुभाग, शब्द, दायित्व, भुगतान, नोटिस अवधि, नियम या विषय से खोजें।',searchPlaceholder:'जैसे: जमा, नवीनीकरण, नोटिस…',clear:'साफ़ करें',matches:'मिलते अनुभाग मिले',oneMatch:'मिलता अनुभाग मिला',needsReview:'समीक्षा आवश्यक',acceptable:'स्वीकार्य दिखता है',viewReview:'धारा समीक्षा में देखें',noMatch:'कोई मिलता अनुभाग नहीं मिला। छोटा शब्द आज़माएँ।',
  reviewReason:'समीक्षा का कारण',automatedReview:'स्वचालित दस्तावेज़ समीक्षा',reviewExplanation:'इस धारा की शर्तों को स्पष्ट करने या उन पर बातचीत करने की आवश्यकता हो सकती है।',needsAttention:'ध्यान आवश्यक',power:'बातचीत शक्ति अनुमान',powerNote:'चिह्नित धाराओं पर आधारित अनुमान, प्रमाणित कानूनी स्कोर नहीं।',
  tracker:'जुर्माना और मुआवज़ा ट्रैकर',applicantPenalties:'आवेदक पर जुर्माना',trigger:'कारण',consequence:'परिणाम',fairness:'निष्पक्षता जाँच',fairnessNote:'जाँचें कि परिणाम स्पष्ट, पारस्परिक, सीमित और अनुपातिक है।',agreementTerm:'समझौते की शर्त',noAmount:'राशि स्पष्ट नहीं है',
  letter:'बातचीत पत्र',copy:'पत्र कॉपी करें',copied:'कॉपी किया',letterCaption:'व्यक्तिगत बनाकर भेजने योग्य धारा-विशिष्ट मसौदा। सभी विवरण स्वतंत्र रूप से जाँचें।',legalHelp:'मानवीय कानूनी सहायता लें',legalHelpIntro:'मामला गंभीर लगे तो ये संगठन मुफ्त या कम लागत में सहायता कर सकते हैं।',disclaimerTitle:'अपने विकल्प समझें—यह कानूनी राय नहीं है',disclaimerFallback:'यह कानूनी सलाह नहीं है। अपने मामले के लिए लाइसेंस प्राप्त विशेषज्ञ से सलाह लें।',download:'पूरी PDF रिपोर्ट डाउनलोड करें',
};

const kn = {
  section:'ವಿಭಾಗ',timeline:'ಕಾಲರೇಖೆ ಮತ್ತು ನೋಟಿಸ್ ಅವಧಿ',jurisdictionAwareness:'ನ್ಯಾಯವ್ಯಾಪ್ತಿ ಮಾಹಿತಿ',emergency:'ತುರ್ತು ಎಚ್ಚರಿಕೆಗಳು',rights:'ಹಕ್ಕು ಉಲ್ಲಂಘನೆ ಸೂಚ್ಯಂಕ',noEmergency:'ಯಾವುದೇ ತುರ್ತು ಎಚ್ಚರಿಕೆ ಕಂಡುಬಂದಿಲ್ಲ.',jurisdiction:'ನ್ಯಾಯವ್ಯಾಪ್ತಿ',notSpecified:'ಸೂಚಿಸಿಲ್ಲ',jurisdictionMissing:'ನ್ಯಾಯವ್ಯಾಪ್ತಿ ಸೂಚಿಸಿಲ್ಲ; ಅನ್ವಯಿಸುವ ಕಾನೂನನ್ನು ವಿಶ್ವಾಸಾರ್ಹವಾಗಿ ಅಳೆಯಲಾಗದು.',timelinePeriods:'ಕಾಲರೇಖೆ ಮತ್ತು ನೋಟಿಸ್ ಅವಧಿಗಳು',noTimeline:'ಸ್ಪಷ್ಟ ಕಾಲರೇಖೆ ಇಲ್ಲ. ಇದು ಕಾನೂನು ಅಪಾಯವಾಗಬಹುದು.',emergencyHeading:'ತುರ್ತು ಎಚ್ಚರಿಕೆಗಳು',emergencyIntro:'ಈ ಷರತ್ತುಗಳು ಪ್ರಮುಖ ಕಾನೂನು ರಕ್ಷಣೆಯನ್ನು ತೆಗೆದುಹಾಕಬಹುದು. ಸಹಿ ಮಾಡುವ ಮೊದಲು ಸಲಹೆ ಪಡೆಯಿರಿ.',violatedRights:'ಉಲ್ಲಂಘನೆಯಾಗಬಹುದಾದ ಹಕ್ಕುಗಳು',legalEffect:'ನಿಖರ ಕಾನೂನು ಪರಿಣಾಮವು ದಾಖಲೆ, ಸಂಗತಿಗಳು ಮತ್ತು ಕಾನೂನಿನ ಮೇಲೆ ಅವಲಂಬಿತವಾಗಿದೆ.',rightsIndex:'ಹಕ್ಕು ಉಲ್ಲಂಘನೆ ಸೂಚ್ಯಂಕ',rightsConcern:'ಸಂಭಾವ್ಯ ಹಕ್ಕು ಸಮಸ್ಯೆಗಳು ಕಂಡುಬಂದಿವೆ.',noRightsConcern:'ಯಾವುದೇ ಸೂಚ್ಯಂಕಿತ ಹಕ್ಕು ಉಲ್ಲಂಘನೆ ಕಂಡುಬಂದಿಲ್ಲ.',low:'ಕಡಿಮೆ',medium:'ಮಧ್ಯಮ',high:'ಹೆಚ್ಚು',accessJustice:'ನ್ಯಾಯದ ಪ್ರವೇಶ',fairTerms:'ನ್ಯಾಯಸಮ್ಮತ ಒಪ್ಪಂದ ಷರತ್ತುಗಳು',privacy:'ಗೌಪ್ಯತೆ',consumerRights:'ಗ್ರಾಹಕ ಹಕ್ಕುಗಳು',employmentRights:'ಉದ್ಯೋಗ ಹಕ್ಕುಗಳು',housingRights:'ವಸತಿ ಹಕ್ಕುಗಳು',financialRights:'ಹಣಕಾಸು ಹಕ್ಕುಗಳು',
  reportSections:'ವರದಿ ವಿಭಾಗಗಳು',selectSection:'ತೆರೆಯಲು ವಿಭಾಗ ಆಯ್ಕೆಮಾಡಿ',navSummary:'ಒಪ್ಪಂದ ಸಾರಾಂಶ',navTimeline:'ಕಾಲರೇಖೆ ಮತ್ತು ನೋಟಿಸ್',navJurisdiction:'ನ್ಯಾಯವ್ಯಾಪ್ತಿ',navEmergency:'ತುರ್ತು ಎಚ್ಚರಿಕೆ',navRights:'ಹಕ್ಕು ಸೂಚ್ಯಂಕ',navLaws:'ಅನ್ವಯಿಸುವ ಕಾನೂನು',navClauseSummary:'ಷರತ್ತು ಸಾರಾಂಶ',navSearch:'ದಾಖಲೆ ಹುಡುಕಿ',navReview:'ಬಣ್ಣದ ಪರಿಶೀಲನೆ',navPenalties:'ದಂಡ ಮತ್ತು ಪರಿಹಾರ',navHidden:'ಗುಪ್ತ ವೆಚ್ಚಗಳು',navLetter:'ಮಾತುಕತೆ ಪತ್ರ',navHelp:'ಕಾನೂನು ಸಹಾಯ',
  laws:'ಅನ್ವಯಿಸುವ ಕಾನೂನು ಮತ್ತು ನಿಯಮಗಳು',lawsCaption:'ಹೊಂದಾಣಿಕೆಯ ನಿಯಮಗಳಿಂದ ಸಕ್ರಿಯವಾದ ಉಲ್ಲೇಖಗಳು. ಅನ್ವಯವು ನ್ಯಾಯವ್ಯಾಪ್ತಿ ಮತ್ತು ಸಂಗತಿಗಳ ಮೇಲೆ ಅವಲಂಬಿತವಾಗಿದೆ.',noLaws:'ಯಾವುದೇ ಕಾನೂನು ಉಲ್ಲೇಖ ಸಕ್ರಿಯವಾಗಿಲ್ಲ. ಕಾನೂನು ಅನ್ವಯಿಸುವುದಿಲ್ಲ ಎಂದರ್ಥವಲ್ಲ.',verification:'ಪರಿಶೀಲನೆ ಅಗತ್ಯ',applicable:'ಅನ್ವಯಿಸುವ ಉಲ್ಲೇಖ',
  search:'ಈ ದಾಖಲೆಯಲ್ಲಿ ಹುಡುಕಿ',searchCaption:'ವಿಭಾಗ, ಪದ, ಹೊಣೆಗಾರಿಕೆ, ಪಾವತಿ, ನೋಟಿಸ್ ಅಥವಾ ವಿಷಯದಿಂದ ಹುಡುಕಿ.',searchPlaceholder:'ಉದಾ: ಠೇವಣಿ, ನವೀಕರಣ, ನೋಟಿಸ್…',clear:'ಅಳಿಸಿ',matches:'ಹೊಂದುವ ವಿಭಾಗಗಳು ಕಂಡಿವೆ',oneMatch:'ಹೊಂದುವ ವಿಭಾಗ ಕಂಡಿದೆ',needsReview:'ಪರಿಶೀಲನೆ ಅಗತ್ಯ',acceptable:'ಸ್ವೀಕಾರಾರ್ಹವಾಗಿದೆ',viewReview:'ಷರತ್ತು ಪರಿಶೀಲನೆಯಲ್ಲಿ ನೋಡಿ',noMatch:'ಹೊಂದುವ ವಿಭಾಗ ಸಿಗಲಿಲ್ಲ. ಚಿಕ್ಕ ಪದ ಪ್ರಯತ್ನಿಸಿ.',
  reviewReason:'ಪರಿಶೀಲನೆ ಕಾರಣ',automatedReview:'ಸ್ವಯಂಚಾಲಿತ ದಾಖಲೆ ಪರಿಶೀಲನೆ',reviewExplanation:'ಈ ಷರತ್ತಿಗೆ ಸ್ಪಷ್ಟೀಕರಣ ಅಥವಾ ಮಾತುಕತೆ ಅಗತ್ಯವಾಗಬಹುದು.',needsAttention:'ಗಮನ ಅಗತ್ಯ',power:'ಮಾತುಕತೆ ಶಕ್ತಿ ಅಂದಾಜು',powerNote:'ಗುರುತಿಸಿದ ಷರತ್ತುಗಳ ಆಧಾರದ ಅಂದಾಜು; ಪ್ರಮಾಣಿತ ಕಾನೂನು ಅಂಕವಲ್ಲ.',
  tracker:'ದಂಡ ಮತ್ತು ಪರಿಹಾರ ಟ್ರ್ಯಾಕರ್',applicantPenalties:'ಅರ್ಜಿದಾರರ ದಂಡಗಳು',trigger:'ಕಾರಣ',consequence:'ಪರಿಣಾಮ',fairness:'ನ್ಯಾಯಸಮ್ಮತತೆ ಪರಿಶೀಲನೆ',fairnessNote:'ಪರಿಣಾಮ ಸ್ಪಷ್ಟ, ಪರಸ್ಪರ, ಮಿತಿಯ ಮತ್ತು ಪ್ರಮಾಣಬದ್ಧವಾಗಿದೆಯೇ ಪರಿಶೀಲಿಸಿ.',agreementTerm:'ಒಪ್ಪಂದದ ಷರತ್ತು',noAmount:'ಮೊತ್ತವನ್ನು ಸ್ಪಷ್ಟವಾಗಿ ತಿಳಿಸಿಲ್ಲ',
  letter:'ಮಾತುಕತೆ ಪತ್ರ',copy:'ಪತ್ರ ನಕಲಿಸಿ',copied:'ನಕಲಿಸಲಾಗಿದೆ',letterCaption:'ವೈಯಕ್ತೀಕರಿಸಿ ಕಳುಹಿಸಲು ಸಿದ್ಧವಾದ ಷರತ್ತು-ನಿರ್ದಿಷ್ಟ ಕರಡು. ವಿವರಗಳನ್ನು ಸ್ವತಂತ್ರವಾಗಿ ಪರಿಶೀಲಿಸಿ.',legalHelp:'ಮಾನವ ಕಾನೂನು ಸಹಾಯ ಪಡೆಯಿರಿ',legalHelpIntro:'ವಿಷಯ ಗಂಭೀರವೆನಿಸಿದರೆ ಈ ಸಂಸ್ಥೆಗಳು ಉಚಿತ ಅಥವಾ ಕಡಿಮೆ ವೆಚ್ಚದಲ್ಲಿ ಸಹಾಯ ಮಾಡಬಹುದು.',disclaimerTitle:'ನಿಮ್ಮ ಆಯ್ಕೆಗಳನ್ನು ತಿಳಿಯಿರಿ—ಇದು ಕಾನೂನು ಅಭಿಪ್ರಾಯವಲ್ಲ',disclaimerFallback:'ಇದು ಕಾನೂನು ಸಲಹೆಯಲ್ಲ. ನಿಮ್ಮ ಪರಿಸ್ಥಿತಿಗೆ ಪರವಾನಗಿ ಪಡೆದ ತಜ್ಞರನ್ನು ಸಂಪರ್ಕಿಸಿ.',download:'ಸಂಪೂರ್ಣ PDF ವರದಿ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ',
};

const ta = {
  section:'பிரிவு',timeline:'காலவரிசை மற்றும் அறிவிப்பு காலம்',jurisdictionAwareness:'அதிகார வரம்பு தகவல்',emergency:'அவசர எச்சரிக்கைகள்',rights:'உரிமை மீறல் குறியீடு',noEmergency:'அவசர எச்சரிக்கை எதுவும் கண்டறியப்படவில்லை.',jurisdiction:'அதிகார வரம்பு',notSpecified:'குறிப்பிடப்படவில்லை',jurisdictionMissing:'அதிகார வரம்பு குறிப்பிடப்படாததால் பொருந்தும் சட்டத்தை நம்பகமாக மதிப்பிட முடியாது.',timelinePeriods:'காலவரிசை மற்றும் அறிவிப்பு காலங்கள்',noTimeline:'தெளிவான காலவரிசை இல்லை. இது சட்ட அபாயமாக இருக்கலாம்.',emergencyHeading:'அவசர எச்சரிக்கைகள்',emergencyIntro:'இந்த விதிகள் முக்கிய சட்டப் பாதுகாப்புகளை நீக்கலாம். கையொப்பமிடும் முன் ஆலோசனை பெறுங்கள்.',violatedRights:'மீறப்படக்கூடிய உரிமைகள்',legalEffect:'சரியான சட்ட விளைவு ஆவணம், உண்மைகள் மற்றும் சட்டத்தைப் பொறுத்தது.',rightsIndex:'உரிமை மீறல் குறியீடு',rightsConcern:'சாத்தியமான உரிமை சிக்கல்கள் கண்டறியப்பட்டன.',noRightsConcern:'உரிமை மீறல் எதுவும் கண்டறியப்படவில்லை.',low:'குறைவு',medium:'நடுத்தரம்',high:'அதிகம்',accessJustice:'நீதியை அணுகுதல்',fairTerms:'நியாயமான ஒப்பந்த விதிகள்',privacy:'தனியுரிமை',consumerRights:'நுகர்வோர் உரிமைகள்',employmentRights:'வேலை உரிமைகள்',housingRights:'வீட்டு உரிமைகள்',financialRights:'நிதி உரிமைகள்',
  reportSections:'அறிக்கை பிரிவுகள்',selectSection:'திறக்க ஒரு பிரிவைத் தேர்ந்தெடுக்கவும்',navSummary:'ஒப்பந்தச் சுருக்கம்',navTimeline:'காலவரிசை மற்றும் அறிவிப்பு',navJurisdiction:'அதிகார வரம்பு',navEmergency:'அவசர எச்சரிக்கை',navRights:'உரிமை குறியீடு',navLaws:'பொருந்தும் சட்டங்கள்',navClauseSummary:'விதி சுருக்கம்',navSearch:'ஆவணத்தில் தேடுக',navReview:'வண்ண ஆய்வு',navPenalties:'அபராதம் மற்றும் இழப்பீடு',navHidden:'மறைமுக செலவுகள்',navLetter:'பேச்சுவார்த்தை கடிதம்',navHelp:'சட்ட உதவி',
  laws:'பொருந்தும் சட்டங்களும் விதிகளும்',lawsCaption:'பொருந்திய விதிகளால் செயல்பட்ட குறிப்புகள். பொருந்துதல் அதிகார வரம்பு மற்றும் உண்மைகளைப் பொறுத்தது.',noLaws:'சட்டக் குறிப்பு எதுவும் செயல்படவில்லை. சட்டம் பொருந்தாது என்று இதற்கு அர்த்தமல்ல.',verification:'சரிபார்ப்பு தேவை',applicable:'பொருந்தும் குறிப்பு',
  search:'இந்த ஆவணத்தில் தேடுக',searchCaption:'பிரிவு, சொல், கடமை, கட்டணம், அறிவிப்பு அல்லது தலைப்பால் தேடுக.',searchPlaceholder:'எ.கா: வைப்புத்தொகை, புதுப்பிப்பு, அறிவிப்பு…',clear:'அழி',matches:'பொருந்தும் பிரிவுகள் கிடைத்தன',oneMatch:'பொருந்தும் பிரிவு கிடைத்தது',needsReview:'ஆய்வு தேவை',acceptable:'ஏற்கத்தக்கதாக உள்ளது',viewReview:'விதி ஆய்வில் காண்க',noMatch:'பொருந்தும் பிரிவு கிடைக்கவில்லை. குறுகிய சொல்லை முயற்சிக்கவும்.',
  reviewReason:'ஆய்வுக்கான காரணம்',automatedReview:'தானியங்கி ஆவண ஆய்வு',reviewExplanation:'இந்த விதிக்கு விளக்கம் அல்லது பேச்சுவார்த்தை தேவைப்படலாம்.',needsAttention:'கவனம் தேவை',power:'பேச்சுவார்த்தை வலிமை மதிப்பீடு',powerNote:'குறிக்கப்பட்ட விதிகளின் அடிப்படையிலான மதிப்பீடு; சான்றளிக்கப்பட்ட சட்ட மதிப்பெண் அல்ல.',
  tracker:'அபராதம் மற்றும் இழப்பீடு கண்காணிப்பு',applicantPenalties:'விண்ணப்பதாரர் அபராதங்கள்',trigger:'காரணம்',consequence:'விளைவு',fairness:'நியாயத்தன்மை சோதனை',fairnessNote:'விளைவு தெளிவானதா, பரஸ்பரமானதா, வரம்புடையதா, விகிதாசாரமானதா என சரிபார்க்கவும்.',agreementTerm:'ஒப்பந்த விதி',noAmount:'தொகை தெளிவாக குறிப்பிடப்படவில்லை',
  letter:'பேச்சுவார்த்தை கடிதம்',copy:'கடிதத்தை நகலெடு',copied:'நகலெடுக்கப்பட்டது',letterCaption:'தனிப்பயனாக்கி அனுப்பத் தயாரான விதி சார்ந்த வரைவு. விவரங்களைத் தனியாகச் சரிபார்க்கவும்.',legalHelp:'மனித சட்ட உதவி பெறுக',legalHelpIntro:'விஷயம் தீவிரமாக இருந்தால் இந்நிறுவனங்கள் இலவசமாக அல்லது குறைந்த செலவில் உதவும்.',disclaimerTitle:'உங்கள் விருப்பங்களை அறியுங்கள்—இது சட்டக் கருத்தல்ல',disclaimerFallback:'இது சட்ட ஆலோசனை அல்ல. உங்கள் சூழ்நிலைக்கு உரிமம் பெற்ற நிபுணரை அணுகவும்.',download:'முழு PDF அறிக்கையைப் பதிவிறக்கவும்',
};

const te = {
  section:'విభాగం',timeline:'కాలక్రమం మరియు నోటీసు వ్యవధి',jurisdictionAwareness:'అధికార పరిధి సమాచారం',emergency:'అత్యవసర హెచ్చరికలు',rights:'హక్కుల ఉల్లంఘన సూచిక',noEmergency:'అత్యవసర హెచ్చరిక ఏదీ కనబడలేదు.',jurisdiction:'అధికార పరిధి',notSpecified:'పేర్కొనలేదు',jurisdictionMissing:'అధికార పరిధి పేర్కొనలేదు; వర్తించే చట్టాన్ని నమ్మకంగా అంచనా వేయలేము.',timelinePeriods:'కాలక్రమం మరియు నోటీసు వ్యవధులు',noTimeline:'స్పష్టమైన కాలక్రమం లేదు. ఇది చట్టపరమైన ప్రమాదం కావచ్చు.',emergencyHeading:'అత్యవసర హెచ్చరికలు',emergencyIntro:'ఈ నిబంధనలు ముఖ్యమైన చట్టపరమైన రక్షణలను తొలగించవచ్చు. సంతకం ముందు సలహా పొందండి.',violatedRights:'ఉల్లంఘించబడే హక్కులు',legalEffect:'ఖచ్చితమైన చట్టపరమైన ప్రభావం పత్రం, వాస్తవాలు మరియు చట్టంపై ఆధారపడుతుంది.',rightsIndex:'హక్కుల ఉల్లంఘన సూచిక',rightsConcern:'సంభావ్య హక్కుల సమస్యలు కనబడ్డాయి.',noRightsConcern:'హక్కుల ఉల్లంఘన ఏదీ కనబడలేదు.',low:'తక్కువ',medium:'మధ్యస్థం',high:'ఎక్కువ',accessJustice:'న్యాయం పొందే హక్కు',fairTerms:'న్యాయమైన ఒప్పంద నిబంధనలు',privacy:'గోప్యత',consumerRights:'వినియోగదారు హక్కులు',employmentRights:'ఉద్యోగ హక్కులు',housingRights:'గృహ హక్కులు',financialRights:'ఆర్థిక హక్కులు',
  reportSections:'నివేదిక విభాగాలు',selectSection:'తెరవడానికి విభాగాన్ని ఎంచుకోండి',navSummary:'ఒప్పంద సారాంశం',navTimeline:'కాలక్రమం మరియు నోటీసు',navJurisdiction:'అధికార పరిధి',navEmergency:'అత్యవసర హెచ్చరిక',navRights:'హక్కుల సూచిక',navLaws:'వర్తించే చట్టాలు',navClauseSummary:'నిబంధన సారాంశం',navSearch:'పత్రంలో వెతకండి',navReview:'రంగు సమీక్ష',navPenalties:'జరిమానా మరియు పరిహారం',navHidden:'దాచిన ఖర్చులు',navLetter:'చర్చా లేఖ',navHelp:'చట్ట సహాయం',
  laws:'వర్తించే చట్టాలు మరియు నియమాలు',lawsCaption:'సరిపోలిన నియమాల ద్వారా సక్రియమైన సూచనలు. వర్తింపు అధికార పరిధి మరియు వాస్తవాలపై ఆధారపడుతుంది.',noLaws:'చట్ట సూచన ఏదీ సక్రియం కాలేదు. చట్టం వర్తించదని దీని అర్థం కాదు.',verification:'ధృవీకరణ అవసరం',applicable:'వర్తించే సూచన',
  search:'ఈ పత్రంలో వెతకండి',searchCaption:'విభాగం, పదం, బాధ్యత, చెల్లింపు, నోటీసు లేదా అంశంతో వెతకండి.',searchPlaceholder:'ఉదా: డిపాజిట్, పునరుద్ధరణ, నోటీసు…',clear:'తొలగించు',matches:'సరిపోలిన విభాగాలు దొరికాయి',oneMatch:'సరిపోలిన విభాగం దొరికింది',needsReview:'సమీక్ష అవసరం',acceptable:'ఆమోదయోగ్యంగా ఉంది',viewReview:'నిబంధన సమీక్షలో చూడండి',noMatch:'సరిపోలిన విభాగం దొరకలేదు. చిన్న పదం ప్రయత్నించండి.',
  reviewReason:'సమీక్ష కారణం',automatedReview:'స్వయంచాలక పత్ర సమీక్ష',reviewExplanation:'ఈ నిబంధనకు వివరణ లేదా చర్చ అవసరం కావచ్చు.',needsAttention:'శ్రద్ధ అవసరం',power:'చర్చా శక్తి అంచనా',powerNote:'గుర్తించిన నిబంధనల ఆధారిత అంచనా; ధృవీకరించిన చట్ట స్కోరు కాదు.',
  tracker:'జరిమానా మరియు పరిహార ట్రాకర్',applicantPenalties:'దరఖాస్తుదారు జరిమానాలు',trigger:'కారణం',consequence:'పరిణామం',fairness:'న్యాయసమ్మతత తనిఖీ',fairnessNote:'పరిణామం స్పష్టమా, పరస్పరమా, పరిమితమా, తగినదా తనిఖీ చేయండి.',agreementTerm:'ఒప్పంద నిబంధన',noAmount:'మొత్తం స్పష్టంగా పేర్కొనలేదు',
  letter:'చర్చా లేఖ',copy:'లేఖను కాపీ చేయండి',copied:'కాపీ అయింది',letterCaption:'వ్యక్తిగతీకరించి పంపడానికి సిద్ధమైన నిబంధన-ఆధారిత ముసాయిదా. వివరాలను స్వతంత్రంగా తనిఖీ చేయండి.',legalHelp:'మానవ చట్ట సహాయం పొందండి',legalHelpIntro:'విషయం తీవ్రమైతే ఈ సంస్థలు ఉచితంగా లేదా తక్కువ ఖర్చుతో సహాయం చేస్తాయి.',disclaimerTitle:'మీ ఎంపికలను తెలుసుకోండి—ఇది చట్టపరమైన అభిప్రాయం కాదు',disclaimerFallback:'ఇది చట్ట సలహా కాదు. మీ పరిస్థితికి లైసెన్స్ పొందిన నిపుణుడిని సంప్రదించండి.',download:'పూర్తి PDF నివేదికను డౌన్‌లోడ్ చేయండి',
};

const bn = {
  section:'ধারা',timeline:'সময়রেখা ও নোটিশের সময়কাল',jurisdictionAwareness:'এখতিয়ার সম্পর্কিত তথ্য',emergency:'জরুরি সতর্কতা',rights:'অধিকার ঝুঁকি সূচক',noEmergency:'কোনো জরুরি সতর্কতা পাওয়া যায়নি।',jurisdiction:'এখতিয়ার',notSpecified:'উল্লেখ নেই',jurisdictionMissing:'এখতিয়ার উল্লেখ নেই, তাই প্রযোজ্য আইন নির্ভরযোগ্যভাবে নির্ধারণ করা যায় না।',timelinePeriods:'সময়রেখা ও নোটিশ',noTimeline:'স্পষ্ট সময়রেখা উল্লেখ নেই।',emergencyHeading:'জরুরি সতর্কতা',emergencyIntro:'এই ধারাগুলো গুরুত্বপূর্ণ আইনি সুরক্ষা কমাতে পারে। স্বাক্ষরের আগে আইনজীবীর পরামর্শ নিন।',violatedRights:'সম্ভাব্য প্রভাবিত অধিকার',legalEffect:'সঠিক আইনি প্রভাব নথি, ঘটনা ও প্রযোজ্য আইনের ওপর নির্ভর করে।',rightsIndex:'অধিকার ঝুঁকি সূচক',rightsConcern:'সম্ভাব্য অধিকার-সংক্রান্ত সমস্যা পাওয়া গেছে।',noRightsConcern:'সূচিভুক্ত কোনো অধিকার সমস্যা পাওয়া যায়নি।',low:'কম',medium:'মাঝারি',high:'উচ্চ',accessJustice:'ন্যায়বিচারে প্রবেশাধিকার',fairTerms:'ন্যায্য চুক্তির শর্ত',privacy:'গোপনীয়তা',consumerRights:'ভোক্তা অধিকার',employmentRights:'শ্রম অধিকার',housingRights:'আবাসন অধিকার',financialRights:'আর্থিক অধিকার',
  reportSections:'রিপোর্টের অংশ',selectSection:'খুলতে একটি অংশ বেছে নিন',navSummary:'চুক্তির সারাংশ',navTimeline:'সময়রেখা ও নোটিশ',navJurisdiction:'এখতিয়ার',navEmergency:'জরুরি সতর্কতা',navRights:'অধিকার সূচক',navLaws:'প্রযোজ্য আইন',navClauseSummary:'ধারার সারাংশ',navSearch:'নথিতে খুঁজুন',navReview:'রঙভিত্তিক পর্যালোচনা',navPenalties:'জরিমানা ও ক্ষতিপূরণ',navHidden:'গোপন খরচ',navLetter:'আলোচনার চিঠি',navHelp:'আইনি সহায়তা',
  laws:'প্রযোজ্য আইন ও নিয়ম',lawsCaption:'মিলে যাওয়া নিয়ম থেকে সক্রিয় তথ্যসূত্র। প্রয়োগ এখতিয়ার ও ঘটনার ওপর নির্ভর করে।',noLaws:'কোনো আইনি তথ্যসূত্র সক্রিয় হয়নি। এর অর্থ এই নয় যে কোনো আইন প্রযোজ্য নয়।',verification:'যাচাই প্রয়োজন',applicable:'প্রযোজ্য তথ্যসূত্র',
  search:'এই নথিতে খুঁজুন',searchCaption:'ধারা, পাঠ, দায়িত্ব, অর্থ, নোটিশ, নিয়ম বা বিষয় দিয়ে খুঁজুন।',searchPlaceholder:'যেমন: জামানত, নবায়ন, নোটিশ…',clear:'মুছুন',matches:'টি অংশ মিলেছে',oneMatch:'একটি অংশ মিলেছে',needsReview:'পর্যালোচনা প্রয়োজন',acceptable:'গ্রহণযোগ্য মনে হচ্ছে',viewReview:'ধারা পর্যালোচনায় দেখুন',noMatch:'কোনো অংশ মেলেনি। ছোট শব্দ দিয়ে চেষ্টা করুন।',
  reviewReason:'পর্যালোচনার কারণ',automatedReview:'স্বয়ংক্রিয় নথি পর্যালোচনা',reviewExplanation:'এই ধারায় ব্যাখ্যা বা আলোচনা প্রয়োজন হতে পারে।',needsAttention:'মনোযোগ প্রয়োজন',power:'আলোচনার ক্ষমতার অনুমান',powerNote:'চিহ্নিত ধারার ভিত্তিতে অনুমান; এটি প্রত্যয়িত আইনি স্কোর নয়।',tracker:'জরিমানা ও ক্ষতিপূরণ ট্র্যাকার',applicantPenalties:'আবেদনকারীর জরিমানা',trigger:'শর্ত',consequence:'ফলাফল',fairness:'ন্যায্যতা পরীক্ষা',fairnessNote:'ফলাফলটি স্পষ্ট, পারস্পরিক, সীমিত ও আনুপাতিক কি না দেখুন।',agreementTerm:'চুক্তির শর্ত',noAmount:'অর্থ স্পষ্টভাবে উল্লেখ নেই',
  letter:'আলোচনার চিঠি',copy:'চিঠি কপি করুন',copied:'কপি হয়েছে',letterCaption:'সম্পাদনা ও পাঠানোর জন্য খসড়া। প্রতিটি তথ্য স্বাধীনভাবে যাচাই করুন।',legalHelp:'মানব আইনি সহায়তা নিন',legalHelpIntro:'বিষয়টি গুরুতর হলে এই সংস্থাগুলো বিনামূল্যে বা কম খরচে সাহায্য করতে পারে।',disclaimerTitle:'আপনার বিকল্প বুঝুন; এটি আইনি মতামত নয়',disclaimerFallback:'এটি আইনি পরামর্শ নয়। আপনার পরিস্থিতির জন্য অনুমোদিত পেশাজীবীর পরামর্শ নিন।',download:'সম্পূর্ণ PDF রিপোর্ট ডাউনলোড করুন',
};

const dictionaries = { en, hi, kn, ta, te, bn };
const landing = {
  en:{kicker:'Understand before you sign',hero:'Legal agreements,',heroEm:'made human.',heroText:'Color-coded clauses, grounded rights and practical negotiation help—in your language.',privacy:'Personal details anonymized',rules:'Rule-bound screening',storage:'No server storage'},
  hi:{kicker:'हस्ताक्षर से पहले समझें',hero:'कानूनी समझौते,',heroEm:'सरल भाषा में।',heroText:'रंग-कोडित धाराएँ, अधिकार और व्यावहारिक बातचीत सहायता—आपकी भाषा में।',privacy:'व्यक्तिगत विवरण गुमनाम',rules:'नियम-आधारित जाँच',storage:'सर्वर पर संग्रह नहीं'},
  kn:{kicker:'ಸಹಿ ಮಾಡುವ ಮೊದಲು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ',hero:'ಕಾನೂನು ಒಪ್ಪಂದಗಳು,',heroEm:'ಸರಳ ಭಾಷೆಯಲ್ಲಿ.',heroText:'ಬಣ್ಣ-ಸಂಕೇತಿತ ಷರತ್ತುಗಳು, ಹಕ್ಕುಗಳು ಮತ್ತು ಪ್ರಾಯೋಗಿಕ ಮಾತುಕತೆ ಸಹಾಯ—ನಿಮ್ಮ ಭಾಷೆಯಲ್ಲಿ.',privacy:'ವೈಯಕ್ತಿಕ ವಿವರಗಳು ಅನಾಮಧೇಯ',rules:'ನಿಯಮ ಆಧಾರಿತ ತಪಾಸಣೆ',storage:'ಸರ್ವರ್ ಸಂಗ್ರಹಣೆ ಇಲ್ಲ'},
  ta:{kicker:'கையொப்பமிடும் முன் புரிந்துகொள்ளுங்கள்',hero:'சட்ட ஒப்பந்தங்கள்,',heroEm:'எளிய மொழியில்.',heroText:'வண்ணக் குறியீட்டு விதிகள், உரிமைகள் மற்றும் நடைமுறை பேச்சுவார்த்தை உதவி—உங்கள் மொழியில்.',privacy:'தனிப்பட்ட விவரங்கள் அடையாளம் நீக்கம்',rules:'விதி சார்ந்த சோதனை',storage:'சேவையக சேமிப்பு இல்லை'},
  te:{kicker:'సంతకం చేసే ముందు అర్థం చేసుకోండి',hero:'చట్టపరమైన ఒప్పందాలు,',heroEm:'సులభమైన భాషలో.',heroText:'రంగు-కోడ్ నిబంధనలు, హక్కులు మరియు ఆచరణాత్మక చర్చా సహాయం—మీ భాషలో.',privacy:'వ్యక్తిగత వివరాలు అనామకం',rules:'నియమ ఆధారిత తనిఖీ',storage:'సర్వర్ నిల్వ లేదు'},
  bn:{kicker:'স্বাক্ষরের আগে বুঝুন',hero:'আইনি চুক্তি,',heroEm:'সহজ ভাষায়।',heroText:'রঙভিত্তিক ধারা, অধিকার এবং ব্যবহারিক আলোচনার সহায়তা—আপনার ভাষায়।',privacy:'ব্যক্তিগত তথ্য গোপন করা হয়',rules:'নিয়মভিত্তিক পরীক্ষা',storage:'সার্ভারে সংরক্ষণ নয়'},
};
const generated = {
  en:{obligationNotMet:'The stated obligation is not met',contractualConsequence:'Contractual consequence',penaltyTitle:'Penalties & compensation',penaltyCaption:'All monetary consequences found in the document, grouped by source section.',noPenalty:'No penalties or compensation were found.',duration:'Duration',noticePeriod:'Notice period',date:'Date',deadline:'Recurring deadline',stateAuthority:'Karnataka State Legal Services Authority',districtAuthority:'District Legal Services Authority',nationalAuthority:'National Legal Services Authority',stateHelp:'Free or eligible legal services and guidance for people who qualify.',districtHelp:'Local legal-aid applications and dispute-resolution support.',nationalHelp:'Legal-services eligibility information and referral support.',verifyContact:'Verify current contact details on the organization’s official source before use.'},
  hi:{obligationNotMet:'निर्दिष्ट दायित्व पूरा नहीं किया गया',contractualConsequence:'अनुबंध संबंधी परिणाम',penaltyTitle:'जुर्माना और मुआवज़ा',penaltyCaption:'दस्तावेज़ में मिले सभी आर्थिक परिणाम, स्रोत अनुभाग के अनुसार।',noPenalty:'कोई जुर्माना या मुआवज़ा नहीं मिला।',duration:'अवधि',noticePeriod:'नोटिस अवधि',date:'तारीख',deadline:'दोहराई जाने वाली अंतिम तिथि',stateAuthority:'कर्नाटक राज्य विधिक सेवा प्राधिकरण',districtAuthority:'जिला विधिक सेवा प्राधिकरण',nationalAuthority:'राष्ट्रीय विधिक सेवा प्राधिकरण',stateHelp:'योग्य व्यक्तियों के लिए निःशुल्क या पात्र कानूनी सेवाएँ और मार्गदर्शन।',districtHelp:'स्थानीय कानूनी सहायता आवेदन और विवाद समाधान सहायता।',nationalHelp:'कानूनी सेवा पात्रता और रेफरल सहायता की जानकारी।',verifyContact:'उपयोग से पहले संगठन के आधिकारिक स्रोत पर वर्तमान संपर्क विवरण सत्यापित करें।'},
  kn:{obligationNotMet:'ಸೂಚಿಸಿದ ಹೊಣೆಗಾರಿಕೆಯನ್ನು ಪೂರೈಸಿಲ್ಲ',contractualConsequence:'ಒಪ್ಪಂದದ ಪರಿಣಾಮ',penaltyTitle:'ದಂಡ ಮತ್ತು ಪರಿಹಾರ',penaltyCaption:'ದಾಖಲೆಯಲ್ಲಿ ಕಂಡ ಎಲ್ಲಾ ಹಣಕಾಸಿನ ಪರಿಣಾಮಗಳು, ಮೂಲ ವಿಭಾಗದ ಪ್ರಕಾರ.',noPenalty:'ಯಾವುದೇ ದಂಡ ಅಥವಾ ಪರಿಹಾರ ಕಂಡುಬಂದಿಲ್ಲ.',duration:'ಅವಧಿ',noticePeriod:'ನೋಟಿಸ್ ಅವಧಿ',date:'ದಿನಾಂಕ',deadline:'ಮರುಕಳಿಸುವ ಕೊನೆಯ ದಿನ',stateAuthority:'ಕರ್ನಾಟಕ ರಾಜ್ಯ ಕಾನೂನು ಸೇವೆಗಳ ಪ್ರಾಧಿಕಾರ',districtAuthority:'ಜಿಲ್ಲಾ ಕಾನೂನು ಸೇವೆಗಳ ಪ್ರಾಧಿಕಾರ',nationalAuthority:'ರಾಷ್ಟ್ರೀಯ ಕಾನೂನು ಸೇವೆಗಳ ಪ್ರಾಧಿಕಾರ',stateHelp:'ಅರ್ಹ ವ್ಯಕ್ತಿಗಳಿಗೆ ಉಚಿತ ಅಥವಾ ಅರ್ಹ ಕಾನೂನು ಸೇವೆಗಳು ಮತ್ತು ಮಾರ್ಗದರ್ಶನ.',districtHelp:'ಸ್ಥಳೀಯ ಕಾನೂನು ಸಹಾಯ ಅರ್ಜಿಗಳು ಮತ್ತು ವಿವಾದ ಪರಿಹಾರ ಬೆಂಬಲ.',nationalHelp:'ಕಾನೂನು ಸೇವಾ ಅರ್ಹತೆ ಮತ್ತು ರೆಫರಲ್ ಬೆಂಬಲದ ಮಾಹಿತಿ.',verifyContact:'ಬಳಕೆಗೆ ಮೊದಲು ಸಂಸ್ಥೆಯ ಅಧಿಕೃತ ಮೂಲದಲ್ಲಿ ಪ್ರಸ್ತುತ ಸಂಪರ್ಕವನ್ನು ಪರಿಶೀಲಿಸಿ.'},
  ta:{obligationNotMet:'குறிப்பிட்ட கடமை நிறைவேற்றப்படவில்லை',contractualConsequence:'ஒப்பந்த விளைவு',penaltyTitle:'அபராதம் மற்றும் இழப்பீடு',penaltyCaption:'ஆவணத்தில் கண்ட அனைத்து நிதி விளைவுகளும் மூலப் பிரிவின்படி.',noPenalty:'அபராதம் அல்லது இழப்பீடு எதுவும் கிடைக்கவில்லை.',duration:'காலம்',noticePeriod:'அறிவிப்பு காலம்',date:'தேதி',deadline:'தொடர் கடைசி நாள்',stateAuthority:'கர்நாடக மாநில சட்ட சேவைகள் ஆணையம்',districtAuthority:'மாவட்ட சட்ட சேவைகள் ஆணையம்',nationalAuthority:'தேசிய சட்ட சேவைகள் ஆணையம்',stateHelp:'தகுதியுள்ளவர்களுக்கு இலவச அல்லது தகுதியான சட்ட சேவைகள் மற்றும் வழிகாட்டுதல்.',districtHelp:'உள்ளூர் சட்ட உதவி விண்ணப்பங்கள் மற்றும் தகராறு தீர்வு உதவி.',nationalHelp:'சட்ட சேவை தகுதி மற்றும் பரிந்துரை உதவி தகவல்.',verifyContact:'பயன்படுத்தும் முன் அமைப்பின் அதிகாரப்பூர்வ மூலத்தில் தொடர்பு விவரத்தைச் சரிபார்க்கவும்.'},
  te:{obligationNotMet:'పేర్కొన్న బాధ్యత నెరవేర్చబడలేదు',contractualConsequence:'ఒప్పంద పరిణామం',penaltyTitle:'జరిమానా మరియు పరిహారం',penaltyCaption:'పత్రంలో కనుగొన్న అన్ని ఆర్థిక పరిణామాలు, మూల విభాగం ప్రకారం.',noPenalty:'జరిమానా లేదా పరిహారం ఏదీ కనబడలేదు.',duration:'వ్యవధి',noticePeriod:'నోటీసు వ్యవధి',date:'తేదీ',deadline:'పునరావృత గడువు',stateAuthority:'కర్ణాటక రాష్ట్ర న్యాయ సేవల ప్రాధికార సంస్థ',districtAuthority:'జిల్లా న్యాయ సేవల ప్రాధికార సంస్థ',nationalAuthority:'జాతీయ న్యాయ సేవల ప్రాధికార సంస్థ',stateHelp:'అర్హులకు ఉచిత లేదా అర్హత ఆధారిత న్యాయ సేవలు మరియు మార్గదర్శకం.',districtHelp:'స్థానిక న్యాయ సహాయ దరఖాస్తులు మరియు వివాద పరిష్కార మద్దతు.',nationalHelp:'న్యాయ సేవల అర్హత మరియు సూచన సహాయం సమాచారం.',verifyContact:'ఉపయోగానికి ముందు సంస్థ అధికారిక మూలంలో ప్రస్తుత సంప్రదింపు వివరాలను ధృవీకరించండి.'},
  bn:{obligationNotMet:'উল্লিখিত দায়িত্ব পালন করা হয়নি',contractualConsequence:'চুক্তিগত ফলাফল',penaltyTitle:'জরিমানা ও ক্ষতিপূরণ',penaltyCaption:'নথিতে পাওয়া সব আর্থিক ফলাফল উৎস ধারা অনুযায়ী সাজানো।',noPenalty:'কোনো জরিমানা বা ক্ষতিপূরণ পাওয়া যায়নি।',duration:'সময়কাল',noticePeriod:'নোটিশের সময়কাল',date:'তারিখ',deadline:'পুনরাবৃত্ত সময়সীমা',stateAuthority:'রাজ্য আইনি পরিষেবা কর্তৃপক্ষ',districtAuthority:'জেলা আইনি পরিষেবা কর্তৃপক্ষ',nationalAuthority:'জাতীয় আইনি পরিষেবা কর্তৃপক্ষ',stateHelp:'যোগ্য ব্যক্তিদের জন্য বিনামূল্যে বা যোগ্যতাভিত্তিক আইনি পরিষেবা ও নির্দেশনা।',districtHelp:'স্থানীয় আইনি সহায়তার আবেদন ও বিরোধ নিষ্পত্তি সহায়তা।',nationalHelp:'আইনি পরিষেবার যোগ্যতা ও রেফারেল সম্পর্কিত তথ্য।',verifyContact:'ব্যবহারের আগে সংস্থার সরকারি উৎসে বর্তমান যোগাযোগের তথ্য যাচাই করুন।'},
};
const supplements = {
  en:{clauseSummary:'Clause review summary',clauseSummaryCaption:'A consolidated view of acceptable clauses and clauses needing review or revision.',noneGroup:'No clauses in this group.',safeWhy:'No warning pattern matched the indexed rules. This is a screening result, not a final legal conclusion.',reviewWhy:'This clause matched a warning or consequence pattern and should be clarified or revised before signing.',recommended:'Recommended change',brandTagline:'Agreement rights, made clear',location:'India-wide screening',footer:'Documents are anonymized and not stored after analysis. Not legal advice.',step2:'Step 2 of 2',changeDocument:'Change document',chooseLanguage:'Choose explanation language',languageNote:'The original text stays unchanged.',ready:'Ready to explain in',selectLanguage:'Select one language to continue.',analyze:'Analyze agreement',reading:'Reading your agreement carefully',readingNote:'This may take a minute for longer documents.',stage1:'Removing personal identifiers',stage2:'Separating document sections',stage3:'Checking rules and obligations',stage4:'Preparing your report'},
  hi:{clauseSummary:'धारा समीक्षा सारांश',clauseSummaryCaption:'स्वीकार्य और समीक्षा या बदलाव चाहने वाली धाराओं का संयुक्त सारांश।',noneGroup:'इस समूह में कोई धारा नहीं है।',safeWhy:'सूचीबद्ध नियमों में कोई चेतावनी नहीं मिली। यह प्रारंभिक जाँच है, अंतिम कानूनी निष्कर्ष नहीं।',reviewWhy:'यह धारा चेतावनी या परिणाम पैटर्न से मेल खाती है और हस्ताक्षर से पहले स्पष्ट या संशोधित होनी चाहिए।',recommended:'सुझाया गया बदलाव',brandTagline:'समझौते के अधिकार, सरल रूप में',location:'कर्नाटक, भारत',footer:'दस्तावेज़ गुमनाम किए जाते हैं और जाँच के बाद संग्रहीत नहीं होते। यह कानूनी सलाह नहीं है।',step2:'चरण 2 में से 2',changeDocument:'दस्तावेज़ बदलें',chooseLanguage:'व्याख्या की भाषा चुनें',languageNote:'मूल पाठ अपरिवर्तित रहेगा।',ready:'व्याख्या के लिए तैयार',selectLanguage:'आगे बढ़ने के लिए एक भाषा चुनें।',analyze:'समझौते की जाँच करें',reading:'आपके समझौते को ध्यान से पढ़ा जा रहा है',readingNote:'लंबे दस्तावेज़ में कुछ समय लग सकता है।',stage1:'व्यक्तिगत पहचान हटाई जा रही है',stage2:'दस्तावेज़ अनुभाग अलग किए जा रहे हैं',stage3:'नियम और दायित्व जाँचे जा रहे हैं',stage4:'रिपोर्ट तैयार की जा रही है'},
  kn:{clauseSummary:'ಷರತ್ತು ಪರಿಶೀಲನೆ ಸಾರಾಂಶ',clauseSummaryCaption:'ಸ್ವೀಕಾರಾರ್ಹ ಮತ್ತು ಪರಿಶೀಲನೆ ಅಗತ್ಯವಿರುವ ಷರತ್ತುಗಳ ಒಟ್ಟಾರೆ ನೋಟ.',noneGroup:'ಈ ಗುಂಪಿನಲ್ಲಿ ಷರತ್ತುಗಳಿಲ್ಲ.',safeWhy:'ಸೂಚ್ಯಂಕಿತ ನಿಯಮಗಳಲ್ಲಿ ಎಚ್ಚರಿಕೆ ಕಂಡುಬಂದಿಲ್ಲ. ಇದು ತಪಾಸಣೆ ಮಾತ್ರ, ಅಂತಿಮ ಕಾನೂನು ತೀರ್ಮಾನವಲ್ಲ.',reviewWhy:'ಈ ಷರತ್ತು ಎಚ್ಚರಿಕೆ ಅಥವಾ ಪರಿಣಾಮದ ಮಾದರಿಗೆ ಹೊಂದಿದೆ; ಸಹಿಯ ಮೊದಲು ಸ್ಪಷ್ಟಪಡಿಸಿ ಅಥವಾ ಪರಿಷ್ಕರಿಸಿ.',recommended:'ಶಿಫಾರಸು ಮಾಡಿದ ಬದಲಾವಣೆ',brandTagline:'ಒಪ್ಪಂದದ ಹಕ್ಕುಗಳು, ಸರಳವಾಗಿ',location:'ಕರ್ನಾಟಕ, ಭಾರತ',footer:'ದಾಖಲೆಗಳನ್ನು ಅನಾಮಧೇಯಗೊಳಿಸಲಾಗುತ್ತದೆ ಮತ್ತು ವಿಶ್ಲೇಷಣೆಯ ನಂತರ ಸಂಗ್ರಹಿಸಲಾಗುವುದಿಲ್ಲ. ಇದು ಕಾನೂನು ಸಲಹೆಯಲ್ಲ.',step2:'ಹಂತ 2 ರಲ್ಲಿ 2',changeDocument:'ದಾಖಲೆ ಬದಲಿಸಿ',chooseLanguage:'ವಿವರಣೆಯ ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ',languageNote:'ಮೂಲ ಪಠ್ಯ ಬದಲಾಗುವುದಿಲ್ಲ.',ready:'ವಿವರಣೆಗೆ ಸಿದ್ಧ',selectLanguage:'ಮುಂದುವರಿಯಲು ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ.',analyze:'ಒಪ್ಪಂದ ವಿಶ್ಲೇಷಿಸಿ',reading:'ನಿಮ್ಮ ಒಪ್ಪಂದವನ್ನು ಎಚ್ಚರಿಕೆಯಿಂದ ಓದುತ್ತಿದೆ',readingNote:'ಉದ್ದ ದಾಖಲೆಗಳಿಗೆ ಸ್ವಲ್ಪ ಸಮಯ ಬೇಕಾಗಬಹುದು.',stage1:'ವೈಯಕ್ತಿಕ ಗುರುತು ತೆಗೆದುಹಾಕುತ್ತಿದೆ',stage2:'ದಾಖಲೆ ವಿಭಾಗಿಸುತ್ತಿದೆ',stage3:'ನಿಯಮ ಮತ್ತು ಹೊಣೆಗಾರಿಕೆ ಪರಿಶೀಲಿಸುತ್ತಿದೆ',stage4:'ವರದಿ ಸಿದ್ಧಪಡಿಸುತ್ತಿದೆ'},
  ta:{clauseSummary:'விதி ஆய்வு சுருக்கம்',clauseSummaryCaption:'ஏற்கத்தக்க விதிகளும் ஆய்வு அல்லது திருத்தம் தேவைப்படும் விதிகளும் ஒருங்கிணைந்த பார்வை.',noneGroup:'இந்தக் குழுவில் விதிகள் இல்லை.',safeWhy:'குறியிடப்பட்ட விதிகளில் எச்சரிக்கை பொருந்தவில்லை. இது ஆரம்பச் சோதனை மட்டுமே; இறுதி சட்ட முடிவு அல்ல.',reviewWhy:'இந்த விதி எச்சரிக்கை அல்லது விளைவு மாதிரியுடன் பொருந்துகிறது; கையொப்பத்திற்கு முன் தெளிவுபடுத்தவும் அல்லது திருத்தவும்.',recommended:'பரிந்துரைக்கப்பட்ட மாற்றம்',brandTagline:'ஒப்பந்த உரிமைகள், எளிதாக',location:'கர்நாடகா, இந்தியா',footer:'ஆவணங்கள் அடையாளம் நீக்கப்பட்டு ஆய்வுக்குப் பின் சேமிக்கப்படுவதில்லை. இது சட்ட ஆலோசனை அல்ல.',step2:'படி 2 இல் 2',changeDocument:'ஆவணத்தை மாற்று',chooseLanguage:'விளக்க மொழியைத் தேர்ந்தெடுக்கவும்',languageNote:'மூல உரை மாறாது.',ready:'விளக்கத் தயார்',selectLanguage:'தொடர ஒரு மொழியைத் தேர்ந்தெடுக்கவும்.',analyze:'ஒப்பந்தத்தை ஆய்வு செய்',reading:'உங்கள் ஒப்பந்தம் கவனமாக வாசிக்கப்படுகிறது',readingNote:'நீண்ட ஆவணங்களுக்கு சிறிது நேரம் ஆகலாம்.',stage1:'தனிப்பட்ட அடையாளங்கள் நீக்கப்படுகின்றன',stage2:'ஆவணப் பிரிவுகள் பிரிக்கப்படுகின்றன',stage3:'விதிகளும் கடமைகளும் சரிபார்க்கப்படுகின்றன',stage4:'அறிக்கை தயாராகிறது'},
  te:{clauseSummary:'నిబంధన సమీక్ష సారాంశం',clauseSummaryCaption:'ఆమోదయోగ్యమైన మరియు సమీక్ష లేదా మార్పు అవసరమైన నిబంధనల సమగ్ర దృశ్యం.',noneGroup:'ఈ సమూహంలో నిబంధనలు లేవు.',safeWhy:'సూచిక నియమాల్లో హెచ్చరిక సరిపోలలేదు. ఇది ప్రాథమిక తనిఖీ మాత్రమే; తుది చట్టపరమైన నిర్ణయం కాదు.',reviewWhy:'ఈ నిబంధన హెచ్చరిక లేదా పరిణామ నమూనాతో సరిపోలింది; సంతకం ముందు స్పష్టం చేయాలి లేదా మార్చాలి.',recommended:'సిఫార్సు చేసిన మార్పు',brandTagline:'ఒప్పంద హక్కులు, సులభంగా',location:'కర్ణాటక, భారతదేశం',footer:'పత్రాలు అనామకంగా మార్చబడతాయి మరియు విశ్లేషణ తర్వాత నిల్వ చేయబడవు. ఇది చట్ట సలహా కాదు.',step2:'దశ 2 లో 2',changeDocument:'పత్రాన్ని మార్చండి',chooseLanguage:'వివరణ భాషను ఎంచుకోండి',languageNote:'అసలు పాఠ్యం మారదు.',ready:'వివరణకు సిద్ధం',selectLanguage:'కొనసాగడానికి ఒక భాషను ఎంచుకోండి.',analyze:'ఒప్పందాన్ని విశ్లేషించండి',reading:'మీ ఒప్పందాన్ని జాగ్రత్తగా చదువుతోంది',readingNote:'పొడవైన పత్రాలకు కొంత సమయం పట్టవచ్చు.',stage1:'వ్యక్తిగత గుర్తింపులు తొలగిస్తోంది',stage2:'పత్ర విభాగాలు విడదీస్తోంది',stage3:'నియమాలు మరియు బాధ్యతలు తనిఖీ చేస్తోంది',stage4:'నివేదిక సిద్ధం చేస్తోంది'},
  bn:{clauseSummary:'ধারা পর্যালোচনার সারাংশ',clauseSummaryCaption:'গ্রহণযোগ্য এবং পর্যালোচনা বা পরিবর্তন প্রয়োজন এমন ধারার সম্মিলিত চিত্র।',noneGroup:'এই দলে কোনো ধারা নেই।',safeWhy:'সূচিভুক্ত নিয়মে কোনো সতর্কতা মেলেনি। এটি প্রাথমিক পরীক্ষা, চূড়ান্ত আইনি সিদ্ধান্ত নয়।',reviewWhy:'এই ধারাটি সতর্কতা বা ফলাফলের ধরনের সঙ্গে মিলেছে; স্বাক্ষরের আগে ব্যাখ্যা বা পরিবর্তন করা উচিত।',recommended:'প্রস্তাবিত পরিবর্তন',brandTagline:'চুক্তির অধিকার, সহজ ভাষায়',location:'সমগ্র ভারত পরীক্ষা',footer:'নথির পরিচয় গোপন করা হয় এবং বিশ্লেষণের পরে সংরক্ষণ করা হয় না। এটি আইনি পরামর্শ নয়।',step2:'২টির মধ্যে ধাপ ২',changeDocument:'নথি পরিবর্তন করুন',chooseLanguage:'ব্যাখ্যার ভাষা বেছে নিন',languageNote:'মূল পাঠ অপরিবর্তিত থাকবে।',ready:'ব্যাখ্যার জন্য প্রস্তুত',selectLanguage:'এগোতে একটি ভাষা বেছে নিন।',analyze:'চুক্তি বিশ্লেষণ করুন',reading:'আপনার চুক্তি মনোযোগ দিয়ে পড়া হচ্ছে',readingNote:'দীর্ঘ নথিতে কিছু সময় লাগতে পারে।',stage1:'ব্যক্তিগত পরিচয় সরানো হচ্ছে',stage2:'নথির অংশ আলাদা করা হচ্ছে',stage3:'নিয়ম ও দায়িত্ব পরীক্ষা করা হচ্ছে',stage4:'রিপোর্ট প্রস্তুত করা হচ্ছে'},
};
export const ui = (language, key) =>
  supplements[language]?.[key] ||
  landing[language]?.[key] ||
  generated[language]?.[key] ||
  dictionaries[language]?.[key] ||
  supplements.en[key] ||
  landing.en[key] ||
  generated.en[key] ||
  dictionaries.en[key] ||
  key;
